# Generated by Django 4.2.4 on 2023-11-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Banner_Type', models.CharField(choices=[('Mobile', 'Mobile'), ('System', 'System')], max_length=10)),
                ('Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
