# Generated by Django 4.2.4 on 2023-11-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.ImageField(null=True, upload_to='Banners'),
        ),
    ]
