# Generated by Django 4.2.4 on 2023-11-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_rename_images_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Image', models.ImageField(null=True, upload_to='Partners')),
            ],
        ),
    ]
