# Generated by Django 4.2.4 on 2023-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Image',
            field=models.ImageField(null=True, upload_to='Events'),
        ),
    ]
