# Generated by Django 4.2.4 on 2023-11-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_events_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
