# Generated by Django 4.2.4 on 2024-01-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
