# Generated by Django 5.0 on 2024-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(null=True, upload_to='Premiums')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Premiums')),
                ('Description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
