# Generated by Django 5.0 on 2024-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_double_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
