# Generated by Django 5.0 on 2024-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_alter_premium_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='double',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='single',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
