# Generated by Django 5.0 on 2024-07-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_alter_double_description_alter_single_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premium',
            options={'ordering': ['Name'], 'verbose_name': 'premium', 'verbose_name_plural': 'premiums'},
        ),
    ]
