# Generated by Django 5.0 on 2024-07-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_alter_premium_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_sizes', to='Core.premium')),
            ],
        ),
    ]
