# Generated by Django 5.0 on 2024-07-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_premiumsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='Premiums'),
        ),
    ]
