# Generated by Django 5.0 on 2024-07-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_premium_image3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='single',
            options={'ordering': ['Name'], 'verbose_name': 'single', 'verbose_name_plural': 'singles'},
        ),
        migrations.CreateModel(
            name='SingleSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('single', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_sizes', to='Core.single')),
            ],
        ),
    ]
