# Generated by Django 5.0 on 2024-07-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_alter_single_options_singlesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='Singles'),
        ),
        migrations.AlterField(
            model_name='single',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='Singles'),
        ),
    ]
