# Generated by Django 5.0 on 2024-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_alter_double_options_doublesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='double',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='Singles'),
        ),
    ]
