# Generated by Django 5.0 on 2024-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
