# Generated by Django 5.0 on 2024-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_registerwarranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Contact', models.CharField(max_length=15)),
                ('Warranty', models.CharField(max_length=100, unique=True)),
                ('Dealer', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
