# Generated by Django 5.0 on 2024-07-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_registercomplaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Link', models.CharField(max_length=300)),
            ],
        ),
    ]
