# Generated by Django 5.0 on 2024-07-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0029_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Image',
            field=models.ImageField(null=True, upload_to='Blogs'),
        ),
    ]
