# Generated by Django 5.0 on 2024-07-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_alter_blogs_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Description',
            new_name='Message',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Place',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
