# Generated by Django 4.2.4 on 2023-11-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='session',
            new_name='Key',
        ),
    ]
